In [1]:
import torch

In [43]:
p1 = torch.tensor([0.0,-1,1]) # normal vector for panel 1
p2 = torch.tensor([0.0,1,1]) # normal vector for panel 2
p3 = torch.tensor([1.0,0,1]) # normal vector for panel 3
s = torch.tensor([3.0,5,2]) # sun vector

# normalize into unit vectors
p1 = p1/torch.norm(p1)
p2 = p2/torch.norm(p2)
p3 = p3/torch.norm(p3)
s = s/torch.norm(s)

# build transformation matrix
A = torch.tensor([[p1[0],p1[1],p1[2]],[p2[0],p2[1],p2[2]],[p3[0],p3[1],p3[2]]])

print(p1)
print(p2)
print(p3)
print(s)

tensor([ 0.0000, -0.7071,  0.7071])
tensor([0.0000, 0.7071, 0.7071])
tensor([0.7071, 0.0000, 0.7071])
tensor([0.4867, 0.8111, 0.3244])


In [36]:
# find panel input tensor using dot product. 
d = torch.tensor([[torch.dot(p1,s)],[torch.dot(p2,s)]])
res = torch.mm(A,d)
print(f"sun vector: {s} resut vector: {res}")

sun vector: tensor([0.4867, 0.8111, 0.3244]) resut vector: tensor([[-0.5678],
        [ 0.5678]])


In [31]:
# 