In [1]:
import torch
import matplotlib.pyplot as plt

In [51]:
#Matrix for the free-space propogation of distance d
def free_space(d):
    return torch.tensor([[1.0,d],[0,1]])

#matrix for the flat interface refraction between to dissimilar indexes
def flat_interface(n1,n2):
    return torch.tensor([[1.0,0],[0,n1/n2]])

#matrix for the refraction at a curved interface of radius r
def curved_interface(n1,n2,R):
    return torch.tensor([[1.0,0],[(n1-n2)/(R*n2),n1/n2]])

#matrix for the reflection of a flat mirror
def flat_mirror():
    return torch.tensor([[1.0,0],[0,1]])

#matrix for the reflection from a curved mirror of radius r
def curved_mirror(r):
    return torch.tensor([[1.0,0],[-2/r, 1]])

# matrix for the refraction of a thin lens of focal length f
def thin_lens(f):
    return torch.tensor([[1.0,0],[-1/f, 1]])

# matrix for the thick lens with radii of curvature, thickness, and refraction indexes
def thick_lens(n1,n2,r1,r2,t):
    A = torch.tensor([[1,0],[(n2-n1)/(r2*n1),n2/n1]])
    B = torch.tensor([[1.0, t],[0, 1]])
    C = torch.tensor([[1,0],[(n1-n2)/(r1*n2),n1/n2]])
    return torch.mm(torch.mm(A,B),C)

In [142]:
#Simple Telescope
objective = thin_lens(80) # focal length
distance = free_space(60) # distance between eyepiece and objective
eyepiece = thin_lens(-120) # diverging focal length


In [153]:
#build lens system
telescope_system = torch.mm(eyepiece, distance)
telescope_system = torch.mm(telescope_system, objective)

#determine imaging conditions
object_distance = free_space(240)
telescope_system = torch.mm(telescope_system, object_distance)
image_distance = telescope_system[0,1]
telescope_magnification = telescope_system[1,1]

print(telescope_system)

print(f"Image Distance: {image_distance}mm")
print(f"Magnification: {telescope_magnification}x")


tensor([[ 2.5000e-01,  1.2000e+02],
        [-1.0417e-02, -1.0000e+00]])
Image Distance: 120.0mm
Magnification: -1.0x


In [157]:
# Simple Magnifying Glass
lens = thin_lens(140) #140mm focal length

# determine imaging conditions
object_distance = free_space(25) #100mm distance
mag_system = torch.mm(lens, object_distance)
image_distance = mag_system[0,1]
magnification = mag_system[1,1]
print(mag_system)

object_ray = torch.Tensor([[0],[10]])
image_ray = torch.mm(mag_system, object_ray)

print(image_ray)
print(f"Image Distance: {image_distance}mm")
print(f"Magnification: {magnification}x")

tensor([[ 1.0000e+00,  2.5000e+01],
        [-7.1429e-03,  8.2143e-01]])
tensor([[250.0000],
        [  8.2143]])
Image Distance: 25.0mm
Magnification: 0.8214285373687744x
