In [69]:
import torch
import torch.nn.functional as F

In [208]:
# power method for finding the dominant eigenvalue.
def power_method(A, tolerance):
    v = torch.rand(A.size()[0],1)
    v=v/v.norm()
    prev=torch.zeros(A.size()[0],1)
    while True:
        prev=v
        v=torch.mm(A,v)
        v=v/v.norm()
        if torch.allclose(v,prev,tolerance):
            break
    return v

In [218]:
A=torch.rand(3,3)
torch.linalg.qr(A)

torch.return_types.linalg_qr(
Q=tensor([[-0.1281, -0.0012, -0.9918],
        [-0.8361, -0.5377,  0.1086],
        [-0.5334,  0.8431,  0.0678]]),
R=tensor([[-0.9789, -0.6450, -1.0838],
        [ 0.0000,  0.3141,  0.0423],
        [ 0.0000,  0.0000, -0.1792]]))

tensor([[0.6513],
        [0.7305],
        [0.2056]])


tensor([[ 0.6513+0.j,  0.7795+0.j, -0.3517+0.j],
        [ 0.7305+0.j, -0.2620+0.j, -0.4363+0.j],
        [ 0.2056+0.j, -0.5690+0.j,  0.8282+0.j]])

A: tensor([[0.2047, 0.8233, 0.3227],
        [0.8846, 0.5544, 0.7377],
        [0.1952, 0.0770, 0.3021]])
 v:tensor([[0.3865],
        [0.9439],
        [0.9622]])


tensor([[0.6935],
        [0.3403],
        [0.6350]])


True